In [2]:
ord('a') # Kod Unicode znaku

97

In [4]:
chr(97) # Unicode na znak

'a'

In [1]:
for i in range(256):
    print(f"{i}: '{chr(i)}'")

0: ''
1: ''
2: ''
3: ''
4: ''
5: ''
6: ''
7: ''
8: '
9: '	'
10: '
'
11: '
'
12: '
'
'3: '
14: ''
15: ''
16: ''
17: ''
18: ''
19: ''
20: ''
21: ''
22: ''
23: ''
24: ''
25: ''
26: ''
27: ''
28: '
'
29: '
'
30: '
'
31: ''
32: ' '
33: '!'
34: '"'
35: '#'
36: '$'
37: '%'
38: '&'
39: '''
40: '('
41: ')'
42: '*'
43: '+'
44: ','
45: '-'
46: '.'
47: '/'
48: '0'
49: '1'
50: '2'
51: '3'
52: '4'
53: '5'
54: '6'
55: '7'
56: '8'
57: '9'
58: ':'
59: ';'
60: '<'
61: '='
62: '>'
63: '?'
64: '@'
65: 'A'
66: 'B'
67: 'C'
68: 'D'
69: 'E'
70: 'F'
71: 'G'
72: 'H'
73: 'I'
74: 'J'
75: 'K'
76: 'L'
77: 'M'
78: 'N'
79: 'O'
80: 'P'
81: 'Q'
82: 'R'
83: 'S'
84: 'T'
85: 'U'
86: 'V'
87: 'W'
88: 'X'
89: 'Y'
90: 'Z'
91: '['
92: '\'
93: ']'
94: '^'
95: '_'
96: '`'
97: 'a'
98: 'b'
99: 'c'
100: 'd'
101: 'e'
102: 'f'
103: 'g'
104: 'h'
105: 'i'
106: 'j'
107: 'k'
108: 'l'
109: 'm'
110: 'n'
111: 'o'
112: 'p'
113: 'q'
114: 'r'
115: 's'
116: 't'
117: 'u'
118: 'v'
119: 'w'
120: 'x'
121: 'y'
122: 'z'
12

In [1]:
for i in range(ord('a'), ord('z')+1):
    print(f"{i}: '{chr(i)}'")

97: 'a'
98: 'b'
99: 'c'
100: 'd'
101: 'e'
102: 'f'
103: 'g'
104: 'h'
105: 'i'
106: 'j'
107: 'k'
108: 'l'
109: 'm'
110: 'n'
111: 'o'
112: 'p'
113: 'q'
114: 'r'
115: 's'
116: 't'
117: 'u'
118: 'v'
119: 'w'
120: 'x'
121: 'y'
122: 'z'


In [2]:
for i in range(ord('A'), ord('Z')+1):
    print(f"{i}: '{chr(i)}'")

65: 'A'
66: 'B'
67: 'C'
68: 'D'
69: 'E'
70: 'F'
71: 'G'
72: 'H'
73: 'I'
74: 'J'
75: 'K'
76: 'L'
77: 'M'
78: 'N'
79: 'O'
80: 'P'
81: 'Q'
82: 'R'
83: 'S'
84: 'T'
85: 'U'
86: 'V'
87: 'W'
88: 'X'
89: 'Y'
90: 'Z'


In [3]:
for i in range(ord('0'), ord('9')+1):
    print(f"{i}: '{chr(i)}'")

48: '0'
49: '1'
50: '2'
51: '3'
52: '4'
53: '5'
54: '6'
55: '7'
56: '8'
57: '9'


In [4]:
ord('7')-ord('0')

7

In [5]:
int('7')

7

In [8]:
for c in r"\n\r\t\0\b":
    print(f"{ord(c)}: '{c}'")

92: '\'
110: 'n'
92: '\'
114: 'r'
92: '\'
116: 't'
92: '\'
48: '0'
92: '\'
98: 'b'


In [ ]:
for c in "\n\r\t\0\b":
    print(f"{ord(c)}: '{c}'")

In [10]:
for c in "ąęśćżźńóĄĘŚĆŻŹŃÓ":
    print(f"{ord(c)}: '{c}'")

261: 'ą'
281: 'ę'
347: 'ś'
263: 'ć'
380: 'ż'
378: 'ź'
324: 'ń'
243: 'ó'
260: 'Ą'
280: 'Ę'
346: 'Ś'
262: 'Ć'
379: 'Ż'
377: 'Ź'
323: 'Ń'
211: 'Ó'


In [11]:
for i in [1234, 23456, 128512, 128513, 128514]:
    print(f"{i}: '{chr(i)}'")

1234: 'Ӓ'
23456: '宠'
128512: '😀'
128513: '😁'
128514: '😂'


In [12]:
x = '😂'

In [13]:
x

'😂'

# Napisy

In [14]:
x = "qwertyuiopkląęśćńa"

In [15]:
x

'qwertyuiopkląęśćńa'

In [16]:
x[5]

'y'

In [17]:
x[-1]

'a'

In [18]:
x[5] = 'X'

TypeError: 'str' object does not support item assignment

In [19]:
y = x[:5]+'X'+x[6:]
y

'qwertXuiopkląęśćńa'

In [20]:
x.replace("y", "X")

'qwertXuiopkląęśćńa'

In [21]:
x

'qwertyuiopkląęśćńa'

In [22]:
x.find('e')

2

In [23]:
x.find('ł')

-1

In [25]:
x[x.find('ł')]

'a'

In [26]:
for c in x:
    print(f"{ord(c)}: '{c}'")

113: 'q'
119: 'w'
101: 'e'
114: 'r'
116: 't'
121: 'y'
117: 'u'
105: 'i'
111: 'o'
112: 'p'
107: 'k'
108: 'l'
261: 'ą'
281: 'ę'
347: 'ś'
263: 'ć'
324: 'ń'
97: 'a'


In [27]:
z = "1,2,3,4,5,6"
z

'1,2,3,4,5,6'

In [28]:
z.split(',')

['1', '2', '3', '4', '5', '6']

In [29]:
z = "      abcd       \n\n\n"
z

'      abcd       \n\n\n'

In [30]:
z.strip()

'abcd'

In [31]:
x

'qwertyuiopkląęśćńa'

In [32]:
x.upper()

'QWERTYUIOPKLĄĘŚĆŃA'

In [33]:
z = x+"1234"

In [34]:
z

'qwertyuiopkląęśćńa1234'

In [35]:
z.upper()

'QWERTYUIOPKLĄĘŚĆŃA1234'

In [36]:
(z.upper()).lower()

'qwertyuiopkląęśćńa1234'

In [37]:
x = {}

In [38]:
x["bcd"]=1

In [39]:
x["y"]=2

In [40]:
x

{'bcd': 1, 'y': 2}

# Krótkie deklaracje list

In [41]:
tab = []
for x in range(10):
    tab.append(x**3);
tab

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [42]:
tab2 = [x**3 for x in range(10)]
tab2

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [43]:
tab2 = [(-1)**x * x**3 for x in range(10)]
tab2

[0, -1, 8, -27, 64, -125, 216, -343, 512, -729]

In [44]:
tab2

[0, -1, 8, -27, 64, -125, 216, -343, 512, -729]

In [45]:
tab3 = [x for x in tab2 if x>0]
tab3

[8, 64, 216, 512]

In [46]:
# to nie krotka
kr = (x**3 for x in range(10))
kr

<generator object <genexpr> at 0x000002506DC14EE0>

In [47]:
kr = tuple(x**3 for x in range(10))
kr

(0, 1, 8, 27, 64, 125, 216, 343, 512, 729)

# Ładowanie bibliotek

In [48]:
import numpy

In [49]:
numpy.pi

3.141592653589793

In [50]:
numpy.cos(0.0)

np.float64(1.0)

In [51]:
cos(0.0)

NameError: name 'cos' is not defined

In [52]:
import numpy as np

In [53]:
np.pi

3.141592653589793

In [54]:
np.cos(1)

np.float64(0.5403023058681398)

In [55]:
from numpy import sin

In [56]:
sin(0.0)

np.float64(0.0)

In [57]:
sin(np.pi)

np.float64(1.2246467991473532e-16)

In [58]:
np.exp(1.0)

np.float64(2.718281828459045)

In [59]:
np.arcsin(1.0)

np.float64(1.5707963267948966)

In [60]:
np.log(100)

np.float64(4.605170185988092)

In [61]:
np.log10(100)

np.float64(2.0)

In [62]:
from numpy import *

In [63]:
cos(pi)

np.float64(-1.0)

In [1]:
np

NameError: name 'np' is not defined

# Przypomnienie

In [2]:
a = [7, 3, 6]
a

[7, 3, 6]

In [3]:
b = (1, 7, 2, 3)

In [4]:
b

(1, 7, 2, 3)

In [5]:
c = [-1, 3, 7]

In [6]:
a+c

[7, 3, 6, -1, 3, 7]

In [7]:
a+3*c

[7, 3, 6, -1, 3, 7, -1, 3, 7, -1, 3, 7]

# Algebra liniowa w Pythonie

In [8]:
import numpy as np

In [9]:
x = np.array([7.0, 3., 6.])

In [10]:
x

array([7., 3., 6.])

In [11]:
np.array([7, 3, 6])

array([7, 3, 6])

In [12]:
y = np.array([-1., 3., 7.])
y

array([-1.,  3.,  7.])

In [13]:
type(y)

numpy.ndarray

In [14]:
x + 3*y

array([ 4., 12., 27.])

In [15]:
x - y

array([ 8.,  0., -1.])

In [16]:
2*x

array([14.,  6., 12.])

In [19]:
A = np.array([ [1., 0., 1.], [2., -4., 1.], [-2., 0., 1.], [1., 1., 5.] ])
A

array([[ 1.,  0.,  1.],
       [ 2., -4.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [20]:
A = np.array([
    [1., 0., 1.],
    [2., -4., 1.],
    [-2., 0., 1.],
    [1., 1., 5.]
])
A

array([[ 1.,  0.,  1.],
       [ 2., -4.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [21]:
A.shape

(4, 3)

In [22]:
x.shape

(3,)

In [23]:
A

array([[ 1.,  0.,  1.],
       [ 2., -4.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [24]:
x

array([7., 3., 6.])

In [ ]:
A@x

array([13.,  8., -8., 40.])

In [26]:
A.dot(x)

array([13.,  8., -8., 40.])

In [27]:
np.dot(A, x)

array([13.,  8., -8., 40.])

In [28]:
x@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [29]:
z = np.array([1.,1., -1., -1.])
z

array([ 1.,  1., -1., -1.])

In [30]:
z@A

array([ 4., -5., -4.])

In [31]:
z.dot(A)

array([ 4., -5., -4.])

In [32]:
z@A@x

np.float64(-11.0)

In [33]:
z.shape

(4,)

In [34]:
x@y

np.float64(44.0)

In [35]:
x

array([7., 3., 6.])

In [36]:
y

array([-1.,  3.,  7.])

In [37]:
np.outer(x, y)

array([[-7., 21., 49.],
       [-3.,  9., 21.],
       [-6., 18., 42.]])

In [38]:
np.linalg.norm(x)

np.float64(9.695359714832659)

In [39]:
np.linalg.norm(x, 1)

np.float64(16.0)

In [41]:
np.linalg.norm(x, np.inf)

np.float64(7.0)

In [42]:
x

array([7., 3., 6.])

# Operacje "po elementach" (element-wise, element-by-element)

In [43]:
a = np.array([9., 8., 6.]);
b = np.array([3., 4., 2.]);

In [44]:
a*b

array([27., 32., 12.])

In [45]:
a@b

np.float64(71.0)

In [46]:
a/b

array([3., 2., 3.])

In [47]:
a**b

array([ 729., 4096.,   36.])

In [48]:
np.exp(a)

array([8103.08392758, 2980.95798704,  403.42879349])

In [49]:
a

array([9., 8., 6.])

In [50]:
A

array([[ 1.,  0.,  1.],
       [ 2., -4.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [51]:
np.exp(A)

array([[2.71828183e+00, 1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 1.83156389e-02, 2.71828183e+00],
       [1.35335283e-01, 1.00000000e+00, 2.71828183e+00],
       [2.71828183e+00, 2.71828183e+00, 1.48413159e+02]])

In [53]:
x = np.linspace(-1,1,11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [54]:
np.sin(x)

array([-0.84147098, -0.71735609, -0.56464247, -0.38941834, -0.19866933,
        0.        ,  0.19866933,  0.38941834,  0.56464247,  0.71735609,
        0.84147098])

In [55]:
x*np.sin(x)

array([0.84147098, 0.57388487, 0.33878548, 0.15576734, 0.03973387,
       0.        , 0.03973387, 0.15576734, 0.33878548, 0.57388487,
       0.84147098])

In [57]:
D = np.array([ [1,2], [3,4] ])
E = np.array([ [-1, 1], [3, -2] ])
c = np.array([1, -1])

In [58]:
D

array([[1, 2],
       [3, 4]])

In [59]:
E

array([[-1,  1],
       [ 3, -2]])

In [60]:
c

array([ 1, -1])

In [61]:
D@c

array([-1, -1])

In [62]:
D*c

array([[ 1, -2],
       [ 3, -4]])

In [63]:
D@E

array([[ 5, -3],
       [ 9, -5]])

In [64]:
D*E

array([[-1,  2],
       [ 9, -8]])

In [65]:
D**2

array([[ 1,  4],
       [ 9, 16]])

In [66]:
D@D

array([[ 7, 10],
       [15, 22]])

In [67]:
np.linalg.matrix_power(D, 2)

array([[ 7, 10],
       [15, 22]])

In [68]:
np.linalg.matrix_power(D, 7)

array([[30853, 44966],
       [67449, 98302]])

In [70]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [71]:
a

array([9., 8., 6.])

In [72]:
x = a

In [73]:
x

array([9., 8., 6.])

In [74]:
x + 1

array([10.,  9.,  7.])

In [75]:
x

array([9., 8., 6.])

In [76]:
A + 1

array([[ 2.,  1.,  2.],
       [ 3., -3.,  2.],
       [-1.,  1.,  2.],
       [ 2.,  2.,  6.]])

In [77]:
z

array([ 1.,  1., -1., -1.])

In [78]:
a + z

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [79]:
A

array([[ 1.,  0.,  1.],
       [ 2., -4.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [84]:
# To nie jest kopia
B = A
B

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [81]:
B[1,1] = 77

In [82]:
B

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [83]:
A

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [85]:
C = A.copy()

In [86]:
C

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [87]:
C[2,2] = 22
C

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0., 22.],
       [ 1.,  1.,  5.]])

In [88]:
A

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [90]:
m = 1
n = m
n = 7

In [91]:
m

1

In [92]:
A

array([[ 1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [93]:
A[0,0] = -1

In [94]:
A

array([[-1.,  0.,  1.],
       [ 2., 77.,  1.],
       [-2.,  0.,  1.],
       [ 1.,  1.,  5.]])

In [95]:
A[0,0]

np.float64(-1.0)

In [96]:
A[2,:]

array([-2.,  0.,  1.])

In [97]:
A[2,:] = np.array([1,2,3])

In [98]:
A

array([[-1.,  0.,  1.],
       [ 2., 77.,  1.],
       [ 1.,  2.,  3.],
       [ 1.,  1.,  5.]])

In [99]:
A[:,2]

array([1., 1., 3., 5.])

In [100]:
A[:,2] += 5

In [101]:
A

array([[-1.,  0.,  6.],
       [ 2., 77.,  6.],
       [ 1.,  2.,  8.],
       [ 1.,  1., 10.]])

In [102]:
u = A.flatten()
u

array([-1.,  0.,  6.,  2., 77.,  6.,  1.,  2.,  8.,  1.,  1., 10.])

In [103]:
A

array([[-1.,  0.,  6.],
       [ 2., 77.,  6.],
       [ 1.,  2.,  8.],
       [ 1.,  1., 10.]])

In [104]:
u.reshape(2, 6)

array([[-1.,  0.,  6.,  2., 77.,  6.],
       [ 1.,  2.,  8.,  1.,  1., 10.]])

In [107]:
A[1:3, 0:2]

array([[ 2., 77.],
       [ 1.,  2.]])

In [108]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [111]:
A

array([[-1.,  0.,  6.],
       [ 2., 77.,  6.],
       [ 1.,  2.,  8.],
       [ 1.,  1., 10.]])

In [112]:
A.T

array([[-1.,  2.,  1.,  1.],
       [ 0., 77.,  2.,  1.],
       [ 6.,  6.,  8., 10.]])

In [113]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [114]:
np.zeros((3,7,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [115]:
np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [117]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [118]:
np.diag(x)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [119]:
np.diag(x, -2)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0]])

In [120]:
np.diag(x, 1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0]])

In [121]:
np.diag(A)

array([-1., 77.,  8.])

In [122]:
A

array([[-1.,  0.,  6.],
       [ 2., 77.,  6.],
       [ 1.,  2.,  8.],
       [ 1.,  1., 10.]])

In [123]:
np.diag(np.diag(A))

array([[-1.,  0.,  0.],
       [ 0., 77.,  0.],
       [ 0.,  0.,  8.]])

In [124]:
D

array([[1, 2],
       [3, 4]])

In [125]:
c

array([ 1, -1])

In [126]:
z = np.linalg.solve(D, c)

In [127]:
z

array([-3.,  2.])

In [128]:
D@z

array([ 1., -1.])